name: "CI Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [ 'stable', 'oldstable' ]
    uses: mutility/ci/.github/workflows/go-test.yaml@main
    with:
      show-coverage: file
      go-version: ${{ matrix.go }}
      golangci-lint-config: .github/golangci.yml

  publish:
    strategy:
      fail-fast: false
      matrix:
        go: [ 'stable', 'oldstable' ]
    permissions:
      contents: write
      pull-requests: write
    needs: test
    if: always() && (needs.test.result == 'success')
    uses: mutility/ci/.github/workflows/go-test-publish.yaml@main
    with:
      go-version: ${{ matrix.go }}
      pr-comment: 'edit'
      pr-comment-content: 'link'
